openapi: 3.1.0
x-stoplight:
  id: xss697rk9a92x
info:
  title: Trouw Service
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /huwelijken:
    get:
      summary: Haal alle huwelijken op
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/huwelijk'
      operationId: get-huwelijken
      description: Haal alle huwelijken op
    post:
      summary: Crieër een nieuw huwelijk
      operationId: post-huwelijken
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/huwelijk'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/huwelijk'
  '/huwelijken/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Haal één enkel huwelijk op
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/huwelijk'
      operationId: get-huwelijken-id
    put:
      summary: Werk een huwelijk bij
      operationId: put-huwelijken-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/huwelijk'
    delete:
      summary: Verwijder een huwelijk
      operationId: delete-huwelijken-id
      responses:
        '200':
          description: OK
components:
  schemas:
    huwelijk:
      title: huwelijk
      x-stoplight:
        id: ktufw11iduvhw
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: |
            De unieke identificatie van dit huwelijks
        type:
          type: string
          description: Het type van dit huwelijk
          enum:
            - huwelijk
            - partnerschap
            - omzetting
          example: huwelijk
        partners:
          x-context: schema.conduction.nl/assent
          type: array
          description: 'De in dit huwelijk betrokken partners, te verwijzen naar het instemmingen registers'
          minItems: 1
          maxItems: 2
          items:
            type: string
        locatie:
          x-context: schema.org/Accommodation
          type: string
          description: Verwijzing naar een locatie boeking in de agendaservice (dus niet de locatie zelf)
        ambtenaar:
          type: string
          x-context: schema.conduction.nl/assent
          description: Verwijzing naar een ambtenaar boeking in de agendaservice (dus niet de ambtenaar zelf)
        moment:
          type: string
          format: date-time
          description: Het moment waarop het huwelijk aanvangt
        producten:
          type: array
          description: De bij dit huwelijk gekozen extra producten
          items:
            type: string
        getuigen:
          description: 'De bij dit huwelijk behorende getuigen, minimaal 1 en maximaal 2 per partner'
          type: array
          items:
            type: object
            properties:
              partner:
                x-context: schema.conduction.nl/assent
                type: string
                description: |-
                  De partner waarvoor deze getuigen geteuige is, een getuige kan maar voor één partner getuigen en iedere partner kan maximaal 2 getuigen hebben. Voor een valide huwelijk heeft elke partner minimaal één getuigen nodig.
                  Partner wordt hierbij aangeduide al een instemming
              instemming:
                x-context: schema.conduction.nl/assent
                type: string
                description: De instemming van deze getuige in het IRC
        checklist:
          type: object
          properties:
            partners:
              type: string
              description: Geeft true indien geen problemen of een string indien wel een probleem. Daarbij bevat de string dan de probleem beschrijving
              example: nog niet alle partners hebben ingestemd met het huwelijk
            locatie:
              type: string
              description: Geeft true indien geen problemen of een string indien wel een probleem. Daarbij bevat de string dan de probleem beschrijving
              example: u heeft nog geen locatie gekozen
            ambetenaar:
              type: string
              description: Geeft true indien geen problemen of een string indien wel een probleem. Daarbij bevat de string dan de probleem beschrijving
              example: u heeft nog geen trouw ambtenaar gekozen
            moment:
              type: string
              description: Geeft true indien geen problemen of een string indien wel een probleem. Daarbij bevat de string dan de probleem beschrijving
              example: u heeft nog geen moment van huwelijk/partnerschap gekozen
            producten:
              type: string
              description: Geeft true indien geen problemen of een string indien wel een probleem. Daarbij bevat de string dan de probleem beschrijving
            getuigen:
              type: string
              description: Geeft true indien geen problemen of een string indien wel een probleem. Daarbij bevat de string dan de probleem beschrijving
              example: een van de partners heeft te weinig getuigen
            order:
              type: string
              description: Geeft true indien geen problemen of een string indien wel een probleem. Daarbij bevat de string dan de probleem beschrijving
              example: u heeft uw huwelijk nog niet betaald
            zaak:
              type: string
              description: Geeft true indien geen problemen of een string indien wel een probleem. Daarbij bevat de string dan de probleem beschrijving
          readOnly: true
        order:
          type: string
          description: Verwijzing naar de bij dit huwelijk horende order in het ORC
        zaak:
          type: string
          description: Verwijzing naar het bij dit huwelijk horende zaak in het ZRC
        instemmingGemeente:
          type: string
          description: De verwijzing van de isntemming van de gemeente met het huwelijk of parterschap
      required:
        - id
        - type
